#!/bin/zsh

autoload -U colors && colors

red="$fg_bold[red]"
grn="$fg_bold[green]"
wht="$fg_bold[white]"
rst="$reset_color"

typeset -A errorCount
errorCount=(0 0 2 0 3 0)

for file in $(ls rulefiles/*); do
	node test.js -q $file
	RET=$?

	(( errorCount[$RET]++ ))
	
	case $RET in
		0 ) ;; # Don't do anything if the test exited OK.
		2 ) echo "[Lexer ] error in: $wht${file}$rst" ;;
		3 ) echo "[Parser] error in: $wht${file}$rst" ;;
		* ) echo "[???   ] error in: $wht${file}$rst" ;;
	esac
done

echo
echo "${wht}-- Result:${rst}"

if (( $errorCount[0] > 0 )); then
	echo "Good             : ${grn}$errorCount[0]${rst}"
fi
if (( $errorCount[2] > 0 )); then
	echo "Lexing error     : ${red}$errorCount[2]${rst}"
fi
if (( $errorCount[3] > 0 )); then
	echo "Analysing error  : ${red}$errorCount[3]${rst}"
fi
